### ISSUE TITLE
Finish shop module

### ISSUE THREAD

**Issue by drPavka** [energine-cmf/energine#18]

**Comment by Supme** [comment]
А де дамп базы?

**Comment by drPavka** [comment]
Я его просто закрыл

не будет магазина в ближайшее время

On Sun, Jan 18, 2015 at 10:48 PM, Alexey Agafonov <notifications@github.com>
wrote:

> А де дамп базы?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/energine-cmf/energine/issues/18#issuecomment-70425202>
> .
>



-- 
Pavel Dubenko, web-developer

**Comment by Supme** [comment]
Ясно...
