### ISSUE TITLE
Grid config doesn't work correctly while fetching config param for getRawData() - fields definition are not affected

### ISSUE THREAD

**Issue by andykarpov** [energine-cmf/energine#73]
A working example:
<component name="goodsEditor" module="shop" class="GoodsEditor">
            <params>
                <param name="rights">3</param>
                <param name="tableName">shop_goods</param>
                <param name="config">site/modules/shop/config/GoodsEditor.component.xml</param>
            </params>
        </component>

Something goes wrong if module="share" and class="Grid":

<component name="goodsEditor" module="share" class="Grid">
            <params>
                <param name="rights">3</param>
                <param name="tableName">shop_goods</param>
                <param name="config">site/modules/shop/config/GoodsEditor.component.xml</param>
            </params>
        </component>

**Comment by drPavka** [comment]
Fixed at c027f732ae97bfc6b33c896ac433c07d6afc33e8
