### ISSUE TITLE
Feature request: New field type for price (mysql numeric(10,2)).

### ISSUE THREAD

**Issue by andykarpov** [energine-cmf/energine#75]
What's required:
1) new field type constant in the FieldDescription, let's name it FIELD_TYPE_NUMERIC
2) xslt template for it to render with a proper html attributes, such as regexp
3) server side validation

**Comment by drPavka** [comment]
I propose to name it FIELD_TYPE_MONEY

**Comment by andykarpov** [comment]
Let's name it FIELD_TYPE_MONEY, np :)
But there were a similar type is already exists - FIELD_TYPE_FLOAT. 
Can we use it for mysql numeric(10,2) field ?
Please suggest something ;)

**Comment by wildex** [comment]
+1 to TYPE_NUMERIC, since it will be more generic, then TYPE_MONEY

**Comment by drPavka** [comment]
What's a problem?

We have TYPE_FLOAT to represent floating point fields
and TYPE_MONEY type stored in NUMERIC(10,2) or DECIMAL(10,2) to represent
money data.


On Wed, Feb 25, 2015 at 1:24 PM, wildex <notifications@github.com> wrote:

> +1 to TYPE_NUMERIC, since it will be more generic, then TYPE_MONEY
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/energine-cmf/energine/issues/75#issuecomment-75944701>
> .
>



-- 
Pavel Dubenko, web-developer
