### ISSUE TITLE
Bug: Grid filter unexpectedly shows all filter "where" conditions for certain field types

### ISSUE THREAD

**Issue by andykarpov** [energine-cmf/energine#76]
Example:
We have a boolean field type inside a filter.
Expected values in the "sign" dropdown: отмечено, не отмечено.
Actual values: содержит, не содержит, =, !=, <, >, между, отмечено, не отмечено.
But filter inputs seems works as expected (they always hidden for that field type).

**Comment by drPavka** [comment]
Couldn't reproduce it
I create boolean/tinyint(1) fields (nullable and not null) - everything works as expected

![screenshot from 2015-02-26 12 36 59](https://cloud.githubusercontent.com/assets/2744587/6390346/417fee3e-bdb4-11e4-8aed-bc242dc063ba.png)

**Comment by drPavka** [comment]
reproduced in safari
