### ISSUE TITLE
Feature request: lookup field

### ISSUE THREAD

**Issue by andykarpov** [energine-cmf/energine#79]
To avoid usage of big amount of data in drop-down fields (related by foreign key) it's propose to implement a new field type "lookup" with ability to search across the foreign table and choose a value from the autocompleted list. 
Pros: 
1) it will speed-up form rendering
2) it will be easy for content-managers
3) profit :)
Cons:
1) complex task (a lot of hard work on the client side, some kind of "autocomplete" state needs to be implemented and available globally for the component form, predefined existing form value, etc)
2) we need somehow to define a lookup field to search (not just _name field, but also in some customizable fields, like "product code", "description", etc.  but _name field for the first time is ok).
3) autocomplete list could (possibly) contains more that one column to display.

So, let's discuss this task asap, it's like an urgent feature in my project :)

**Comment by drPavka** [comment]
added
