### ISSUE TITLE
Annoying QAL::select() returns TRUE when empty result given

### ISSUE THREAD

**Issue by andykarpov** [energine-cmf/energine#81]
All what developer needs is to make a select request, like:
$res = $dbh->select() 
and then use result if any, like so:
if ($res) {
    .... do whatever you need with $res
}

But now developer needs to check the result with the following annoying checks:
if ($res and is_array($res)) {
    .... do.....
}

Also that is not clear - what is the FALSE response means ?

**Comment by drPavka** [comment]
fixed
